## Матричный метод

In [3]:
import numpy as np

* -5x+4y=7
*   -8x−6y=9

In [10]:
K = np.array([[-5., 4.], [-8., -6.]])
K

array([[-5.,  4.],
       [-8., -6.]])

In [11]:
L = np.array([7., 9.])
L

array([7., 9.])

In [12]:
np.linalg.solve(K, L)

array([-1.25806452,  0.17741935])

Ответ: -1.25, 0.17